// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIKm7rmwCwvvfpjLePBbNFWcPp09O9_I4',
    appId: '1:1081067066927:android:8a196bf7a1f37e76f318da',
    messagingSenderId: '1081067066927',
    projectId: 'diary1915-878fd',
    databaseURL: 'https://diary1915-878fd-default-rtdb.firebaseio.com',
    storageBucket: 'diary1915-878fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7tovu_D8X3SgU1UdXig5WpiqPfLLYSoM',
    appId: '1:1081067066927:ios:b6f33fa2f17ca923f318da',
    messagingSenderId: '1081067066927',
    projectId: 'diary1915-878fd',
    databaseURL: 'https://diary1915-878fd-default-rtdb.firebaseio.com',
    storageBucket: 'diary1915-878fd.appspot.com',
    iosBundleId: 'com.example.doanCleanAchitec',
  );
}
